apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-deployment
  namespace: bank
  labels:
    app: simple-bank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-bank
  template:
    metadata:
      labels:
        app: simple-bank
    spec:
      containers:
      - name: simple-bank-container
        image: registry.digitalocean.com/foodcage-reg-1/simple_bank:f59c50d
        ports:
        - containerPort: 8080
          name: http-server
